name : Run Postman tests

on:
  push: 
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "00 7 * * *"  #7AM UK time
    - cron: "00 21 * * *" #9PM UK time

jobs:
  run-postman-tests:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.1

    - name: Install Node js and npm
      uses: actions/setup-node@v6.1.0
      with: 
        node-version: '22'

    - name: install npm and htmlextra globally
      run: npm install -g newman
           npm install -g newman-reporter-htmlextra

    - name: Run the postman collection
      run: |
           newman run E2E_flow_API_Tests.postman_collection.json \
           -e QA.postman_environment.json \
           -r cli,htmlextra \
           --reporter-htmlextra-export ./newman/index.html \
           -x

    - name: Newman report
      if: always() #Ensure that reports are generated even if any of the tests fail
      uses: actions/upload-artifact@v6.0.0
      with: 
           name: Newman report
           path: newman/*.html

    - name: Creating github page branch
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: newman/

    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v7
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: E2E Test Execution Notification
        from: ${{secrets.EMAIL_USERNAME}}
        to: ${{secrets.EMAIL_USERNAME}}
        body: |
              Hi,
              Your E2E tests have been executed and the results are published to the URL below :
              https://a-codebee.github.io/APICollectionFiles/
        attachments: newman/index.html
           
   
        
